import re
repl_dict_vi = {
  re.compile("&quot;", re.MULTILINE | re.UNICODE): '"',
	re.compile('&apos;', re.MULTILINE | re.UNICODE): "'",
	re.compile('&#91;', re.MULTILINE | re.UNICODE): '[',
	re.compile('&#93;', re.MULTILINE | re.UNICODE): ']',
	re.compile('&apos;', re.MULTILINE | re.UNICODE): '&',
	re.compile('(?<=\w) (?=[\.\:\?\,\;\!])', re.MULTILINE | re.UNICODE): '',
	re.compile(' eos ', re.MULTILINE | re.UNICODE): ' ',
	re.compile('\. "\n', re.MULTILINE | re.UNICODE): '. " ',
	re.compile('\ \/\ ', re.MULTILINE | re.UNICODE): '/',
	re.compile('(\w) \- (\w)', re.MULTILINE | re.UNICODE): '\g<1>-\g<2>',
	re.compile('\' (.+?) \'', re.MULTILINE | re.UNICODE): "'\g<1>'",
	re.compile('\" (.+?) \"', re.MULTILINE | re.UNICODE): '"\g<1>"',
	re.compile('\[ (.+?) \]', re.MULTILINE | re.UNICODE): '[\g<1>]',
	re.compile('\( (.+?) \)', re.MULTILINE | re.UNICODE): '(\g<1>)',
	re.compile('Đức Mẹ Đồng Trinh', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'trinh nữ',
	re.compile('\bYahweh\b', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Đức Giê-hô-va',
	re.compile('\bUST\b', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'UST',
	re.compile('\bULT\b', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'ULT',
	re.compile('(\d)\: (\d)', re.MULTILINE | re.UNICODE | re.IGNORECASE): '\g<1>:\g<2>',
	re.compile('ki ?-? ?tô', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Christ',
	re.compile('Jêsus', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Giê-xu',
	re.compile('\bJesus\b', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Giê-xu',
	re.compile('đấng christ', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Chúa Cứu Thế',
	re.compile('chúa giê ?- ?xu christ', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Chúa Cứu Thế Giê-xu',
	re.compile('\bChrist\b', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Cứu Thế',
	re.compile('Thần Ðức Chúa Trời', re.MULTILINE | re.UNICODE | re.IGNORECASE): 'Ðức Chúa Trời',
}

clean_dict_html = {
	re.compile('\b[^\u0000-\u007F\u0080-\u00FF\u0100-\u017F\u0180-\u024F\u1E00-\u1EFF\u2000-\u206F\u2200-\u22FF\u20A0-\u20CF]+\b', re.MULTILINE | re.UNICODE): ' ffff ',
	re.compile('[\xa0\u2000-\u200B]', re.MULTILINE | re.UNICODE): ' ',
	re.compile('&amp;', re.MULTILINE | re.UNICODE): '&',
	re.compile('& ?quot ?;', re.MULTILINE | re.UNICODE): '"',
	re.compile('& ?apos ?;', re.MULTILINE | re.UNICODE): "'",
	re.compile('& ?gt ?;', re.MULTILINE | re.UNICODE): '>',
	re.compile('& ?lt ?;', re.MULTILINE | re.UNICODE): '<',
	re.compile('&#?.{,7};', re.MULTILINE | re.UNICODE): '',
	re.compile('<.*?>', re.MULTILINE | re.UNICODE): '',
	re.compile('”|“', re.MULTILINE | re.UNICODE): '',
	re.compile('‘|’', re.MULTILINE | re.UNICODE): "'",
	re.compile("'", re.MULTILINE | re.UNICODE): " ' ",
	re.compile('\[EOS\]', re.MULTILINE | re.UNICODE): 'eos',
	re.compile('\. ?eos', re.MULTILINE | re.UNICODE): ' . eos',
	re.compile('\.\.\.\.[\.\ ]+', re.MULTILINE | re.UNICODE): '....',
	re.compile('\-', re.MULTILINE | re.UNICODE): ' - ',
	re.compile('  +', re.MULTILINE | re.UNICODE): ' ',
	re.compile('\- \-', re.MULTILINE | re.UNICODE): '--',
	re.compile('\. \. \.', re.MULTILINE | re.UNICODE): '...',
}

dictOfReplacementStrings = {
    'thiên chúa': 'Thiên chúa',
}